# Generated by Django 4.0.6 on 2022-07-10 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('income', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='type',
            options={'verbose_name': 'Tipo', 'verbose_name_plural': 'Tipos'},
        ),
        migrations.AlterField(
            model_name='type',
            name='name',
            field=models.CharField(default='', max_length=20, verbose_name='Nombre de tipo de ingreso'),
        ),
    ]
